### PR TITLE
Added support for python3.11, django4.0 and django4.1

### PR DESCRIPTION
**Pull request by 73VW**
I've made the same you've done in https://github.com/roaldnefs/django-sms/commit/cf445bc441066bbe97eeb0eac48faad7ad886e93 and added support for multiple django versions.

I've also fixed a few errors that used to appear during CI tests. 
I've also refactored the init method on SmsBackend in the same time as it could have raised other errors (empty string in `os.path.abspath`)

### CODE REVIEW

**Comment by 73VW** [comment]
Build results: https://github.com/73VW/django-sms/actions/runs/3696313277

**Review by roaldnefs — APPROVED** [review]

**Comment by 73VW** [comment]
Hey @roaldnefs,

Thank you for reviewing this. Do you need anything else on this PR?

Cheers

**Comment by roaldnefs** [comment]
I will update the `CHANGELOG.md` and bump the version later today to be able to create a new release.

Thanks for contributing to this project @73VW.

**Comment by 73VW** [comment]
@roaldnefs Thank you very much!

You're welcome! Hope this helps others

**Comment by 73VW** [comment]
You are too fast, thank you very much!

**Pull request merged**
